# Generated by Django 3.1.7 on 2021-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.IntegerField(null=True)),
                ('isbn_number', models.CharField(blank=True, max_length=15)),
                ('page_count', models.IntegerField(null=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
