# Generated by Django 3.1.7 on 2021-03-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books_api', '0003_auto_20210325_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(blank=True),
        ),
    ]
