# Generated by Django 3.1.7 on 2021-03-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books_api', '0004_auto_20210325_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
