# Generated by Django 3.1.7 on 2021-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books_api', '0005_auto_20210325_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
    ]
